CREATE TABLE categorias (
  id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   titulo VARCHAR(255) NOT NULL,
   descricao VARCHAR(255),
   url_imagem VARCHAR(255),
   CONSTRAINT pk_categorias PRIMARY KEY (id_categoria)
);